music/urls.py
from django.conf.urls import url
from . import views

app_name = "music"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<album_id>[0-9]+)/$', views.details, name='details'),
    url(r'^(?P<album_id>[0-9]+)/favourite/$', views.favourite, name='favourite'),
    url(r'^(?P<album_id>[0-9]+)/unfavourite/$', views.unfavourite, name='unfavourite'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=500)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + '-' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favourite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song
from django.http import Http404
# Create your views here.


def index(request):
    all_albums = Album.objects.all()
    context = {'all_albums': all_albums, }
    return render(request, 'music/index.html', context)

def details(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/details.html', {"album": album, })

def favourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {'album': album, 'error_message': "Cant just do that", })
    else:
        selected_song.is_favourite = True
        selected_song.save()
        return render(request, 'music/details.html', {"album": album, })

def unfavourite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music/details.html', {'album': album, 'error_message': "Cant just do that", })
    else:
        selected_song.is_favourite = False
        selected_song.save()
        return render(request, 'music/details.html', {"album": album, })

music/templates/music/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ album.title }}</title>
</head>
<body>
        <img src = "{{ album.album_logo }}">
        <h1>{{ album.album_title }} - {{ album.song_set.count }}</h1>
        <h3>{{ album.artist }}</h3>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

<form action = "{% url 'music:favourite' album.id %}" method="post">
    {% csrf_token %}
    <ol>
    {% for song in album.song_set.all %}
        <li>
        <input type = "radio" id = "song{{ forloop.counter }}" name="song" value="{{ song.id }}"/>
        <label for ="song{{ forloop.counter }}">{{ song.song_title }}</label>
        {% if song.is_favourite %}
            <span style = "color:red;">*</span>
        {% endif %}
            </li>
    {% endfor %}
        </ol>
    <input type="submit" value="Make Favourite"/>
    <input type="submit" formaction="{% url 'music:unfavourite' album.id %}" value="Unfavourite"/>
</form>
</body>
</html>

music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Albums</title>
</head>
<body>
{% if all_albums %}
        <ul>
            {% for album in all_albums %}
            <li><a href = "{% url 'music:details' album.id %}">{{ album.album_title }}</a></li>
            {% endfor %}
        </ul>

{% else %}
    <h1>You don't have an Album</h1>
{% endif %}
</body>
</html>